"""add new fields to student table

Revision ID: 2730527c8c96
Revises: 
Create Date: 2026-05-12 17:19:29.418526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2730527c8c96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams')
    op.drop_table('parent_student_links')
    op.drop_index(op.f('ix_counselling_sessions_user_id'), table_name='counselling_sessions')
    op.drop_table('counselling_sessions')
    op.drop_index(op.f('ix_human_counsellor_notes_student_id'), table_name='human_counsellor_notes')
    op.drop_table('human_counsellor_notes')
    op.drop_table('counselling_conversation_history')
    op.drop_table('counsellor_student_links')
    op.drop_table('scholarships')
    op.drop_table('careers')
    op.drop_table('colleges')
    op.alter_column('counsellor', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('counsellor', 'active',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('counsellor', 'available_online',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_index(op.f('UKllmcy6qc5mqh7qdj57cer8d1n'), table_name='counsellor')
    op.create_index(op.f('ix_counsellor_counsellor_id'), 'counsellor', ['counsellor_id'], unique=False)
    op.create_index(op.f('ix_counsellor_user_id'), 'counsellor', ['user_id'], unique=True)
    op.create_foreign_key(None, 'counsellor', 'users', ['user_id'], ['id'])
    op.alter_column('school', 'school_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('school', 'active',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('school', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_index(op.f('UKljeoo1brpnabxq3frgdwbe3qv'), table_name='school')
    op.create_index(op.f('ix_school_school_id'), 'school', ['school_id'], unique=False)
    op.create_foreign_key(None, 'school', 'users', ['user_id'], ['id'])
    op.add_column('student', sa.Column('juniorcollege', sa.String(length=255), nullable=True))
    op.add_column('student', sa.Column('college', sa.String(length=255), nullable=True))
    op.add_column('student', sa.Column('contact', sa.Integer().with_variant(mysql.BIGINT(), 'mysql'), nullable=True))
    op.add_column('student', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('student', sa.Column('hobbies', sa.String(length=255), nullable=True))
    op.add_column('student', sa.Column('skills', sa.String(length=255), nullable=True))
    op.alter_column('student', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('student', 'active',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_index(op.f('UKbkix9btnoi1n917ll7bplkvg5'), table_name='student')
    op.create_index(op.f('ix_student_student_id'), 'student', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_user_id'), 'student', ['user_id'], unique=True)
    op.create_foreign_key(None, 'student', 'users', ['user_id'], ['id'])
    op.drop_column('student', 'preferred_language')
    op.alter_column('users', 'verified',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_index(op.f('UK6dotkott2kjsp8vw4d0m25fb7'), table_name='users')
    op.drop_index(op.f('UKdu5v5sr43g5bfnji4vb8hg5s3'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('UKdu5v5sr43g5bfnji4vb8hg5s3'), 'users', ['phone'], unique=True)
    op.create_index(op.f('UK6dotkott2kjsp8vw4d0m25fb7'), 'users', ['email'], unique=True)
    op.alter_column('users', 'verified',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=True)
    op.add_column('student', sa.Column('preferred_language', mysql.VARCHAR(length=255), server_default=sa.text("'English'"), nullable=True))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_index(op.f('ix_student_user_id'), table_name='student')
    op.drop_index(op.f('ix_student_student_id'), table_name='student')
    op.create_index(op.f('UKbkix9btnoi1n917ll7bplkvg5'), 'student', ['user_id'], unique=True)
    op.alter_column('student', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=True)
    op.alter_column('student', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('student', 'skills')
    op.drop_column('student', 'hobbies')
    op.drop_column('student', 'country')
    op.drop_column('student', 'contact')
    op.drop_column('student', 'college')
    op.drop_column('student', 'juniorcollege')
    op.drop_constraint(None, 'school', type_='foreignkey')
    op.drop_index(op.f('ix_school_school_id'), table_name='school')
    op.create_index(op.f('UKljeoo1brpnabxq3frgdwbe3qv'), 'school', ['user_id'], unique=True)
    op.alter_column('school', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('school', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=True)
    op.alter_column('school', 'school_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'counsellor', type_='foreignkey')
    op.drop_index(op.f('ix_counsellor_user_id'), table_name='counsellor')
    op.drop_index(op.f('ix_counsellor_counsellor_id'), table_name='counsellor')
    op.create_index(op.f('UKllmcy6qc5mqh7qdj57cer8d1n'), 'counsellor', ['user_id'], unique=True)
    op.alter_column('counsellor', 'available_online',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=True)
    op.alter_column('counsellor', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=True)
    op.alter_column('counsellor', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.create_table('colleges',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('course', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stream_required', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cutoff_score', mysql.FLOAT(), nullable=True),
    sa.Column('fees', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ranking', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('placements', mysql.TEXT(), nullable=True),
    sa.Column('hostel_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('college_type', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('careers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('career_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('required_skills', mysql.TEXT(), nullable=True),
    sa.Column('average_salary', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('future_scope', mysql.TEXT(), nullable=True),
    sa.Column('stream_required', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scholarships',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scholarship_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('eligibility', mysql.TEXT(), nullable=True),
    sa.Column('amount', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('counsellor_student_links',
    sa.Column('counsellor_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], name=op.f('counsellor_student_links_ibfk_1')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('counsellor_student_links_ibfk_2')),
    sa.PrimaryKeyConstraint('counsellor_id', 'student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('counselling_conversation_history',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['counselling_sessions.session_id'], name=op.f('counselling_conversation_history_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('human_counsellor_notes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_human_counsellor_notes_student_id'), 'human_counsellor_notes', ['student_id'], unique=False)
    op.create_table('counselling_sessions',
    sa.Column('session_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('counselling_mode', mysql.VARCHAR(length=50), server_default=sa.text("'explore'"), nullable=False),
    sa.Column('context', mysql.JSON(), nullable=True),
    sa.Column('summary', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_counselling_sessions_user_id'), 'counselling_sessions', ['user_id'], unique=False)
    op.create_table('parent_student_links',
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('relationship_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('parent_student_links_ibfk_1')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('parent_student_links_ibfk_2')),
    sa.PrimaryKeyConstraint('parent_id', 'student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exams',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exam_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('stream', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('eligibility', mysql.TEXT(), nullable=True),
    sa.Column('exam_date', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('syllabus', mysql.TEXT(), nullable=True),
    sa.Column('mode', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
